//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_FoodCourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public int AdminUserId { get; set; }
        public string AdminUserPassword { get; set; }
        public string EmailID { get; set; }
        public string MobileNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int UserTypeId { get; set; }
        public Nullable<bool> IsLoginEnabled { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
