//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_FoodCourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EWalletTransaction
    {
        public int EwalletId { get; set; }
        public int UserId { get; set; }
        public int RestaurantLocationId { get; set; }
        public int OrderID { get; set; }
        public decimal AmountPaid { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual UserOrder UserOrder { get; set; }
        public virtual RestaurantLocation RestaurantLocation { get; set; }
        public virtual RegisteredUser RegisteredUser { get; set; }
    }
}
