//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_FoodCourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int MenuItemId { get; set; }
        public int MenuID { get; set; }
        public int FoodCategoryId { get; set; }
        public int CusineId { get; set; }
        public int PreparationTime { get; set; }
        public string CusineImage1 { get; set; }
        public string CusineImage2 { get; set; }
        public int Cost { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ItemName { get; set; }
        public bool VEG { get; set; }
    
        public virtual Cuisine Cuisine { get; set; }
        public virtual FoodCategory FoodCategory { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
