//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_FoodCourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.RestaurantLocations = new HashSet<RestaurantLocation>();
        }
    
        public int RestaurantID { get; set; }
        public string RestaurantName { get; set; }
        public int RestaurantTypeId { get; set; }
        public string LogoImagePath { get; set; }
        public Nullable<bool> ResturantStatus { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string ResturantURL { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RestaurantLocation> RestaurantLocations { get; set; }
    }
}
