//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_FoodCourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResturantFacilityMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResturantFacilityMaster()
        {
            this.ResturantFacilities = new HashSet<ResturantFacility>();
        }
    
        public int ResturantFacilityMasterId { get; set; }
        public string FacilityDescription { get; set; }
        public string FacilityIcon { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResturantFacility> ResturantFacilities { get; set; }
    }
}
