//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_FoodCourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResturantFacility
    {
        public int ResturantFacilityId { get; set; }
        public int ResturantFacilityMasterId { get; set; }
        public int RestaurantLocationId { get; set; }
        public Nullable<bool> FacilityStatus { get; set; }
        public Nullable<bool> PaidFacility { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual RestaurantLocation RestaurantLocation { get; set; }
        public virtual ResturantFacilityMaster ResturantFacilityMaster { get; set; }
    }
}
