//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_FoodCourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatReservationDetail
    {
        public int SeatReservationDetail1 { get; set; }
        public int ReservationId { get; set; }
        public int TableId { get; set; }
    
        public virtual ResturantTable ResturantTable { get; set; }
        public virtual SeatReservation SeatReservation { get; set; }
    }
}
