//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_FoodCourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeatReservation()
        {
            this.SeatReservationDetails = new HashSet<SeatReservationDetail>();
        }
    
        public int ReservationId { get; set; }
        public int UserId { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public System.DateTime ReservedDate { get; set; }
        public int RestaurantLocationId { get; set; }
        public int SeatsReserved { get; set; }
        public int ReservationTime { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ProessingStatu ProessingStatu { get; set; }
        public virtual RegisteredUser RegisteredUser { get; set; }
        public virtual UserOrder UserOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatReservationDetail> SeatReservationDetails { get; set; }
    }
}
