//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_FoodCourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrderDetail
    {
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<int> ProcessingStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int UserOrderDetailsId { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual ProessingStatu ProessingStatu { get; set; }
        public virtual UserOrder UserOrder { get; set; }
    }
}
