//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_FoodCourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserOrder()
        {
            this.EWalletTransactions = new HashSet<EWalletTransaction>();
            this.SeatReservations = new HashSet<SeatReservation>();
            this.UserOrderDetails = new HashSet<UserOrderDetail>();
        }
    
        public int OrderID { get; set; }
        public int UserId { get; set; }
        public int RestaurantLocationId { get; set; }
        public int OrderTypeId { get; set; }
        public int StatusId { get; set; }
        public int OfferId { get; set; }
        public decimal Cost { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EWalletTransaction> EWalletTransactions { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual ProessingStatu ProessingStatu { get; set; }
        public virtual RegisteredUser RegisteredUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatReservation> SeatReservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOrderDetail> UserOrderDetails { get; set; }
    }
}
