//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_FoodCourt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReview
    {
        public int ReviewID { get; set; }
        public int UserId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Rating { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public int ResturantId { get; set; }
    
        public virtual RegisteredUser RegisteredUser { get; set; }
    }
}
